version: "3.8"

services:
  db:
    image: postgres:16
    container_name: postgres_container
    environment:
      POSTGRES_USER: cloud_prism
      POSTGRES_PASSWORD: cloud_prism24
      POSTGRES_DB: cloud_prism
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
