export { applicant, applicantRelations } from "./applicant"
export { assementRelations, assessment } from "./assesment"
export { exam, examRelations } from "./exam"
export { jobPositionExams, jobPositionExamsRelation } from "./job-position-exams"
export { option, optionRelations } from "./option"
export { position, positionRelations } from "./postition"
export { question, questionRelations } from "./question"
export { result, resultRelations } from "./result"
export { user, userRelations } from "./user"

